Typed Linear Algebra: fcarouge Namespace Reference
fcarouge Namespace Reference
Francois Carouge's projects namespace.
Namespaces
namespace eigen
namespace internal
Internal implementation details.
namespace test
Unit, integration, regression, and usage tests.
Classes
struct divides
Linear algebra divides expression type specialization point.
struct element_traits
Element traits for conversions.
struct evaluates
Linear algebra evaluates override expression lazy evaluation specialization point.
struct evaluates< Type >
Specialization of the evaluation type.
struct evaluates< TypedMatrix< Matrix, RowIndexes, ColumnIndexes > >
Specialization of the evaluation type.
struct minus
Type minus, subtraction expression type specialization point.
struct multiplies
Type multiplies expression type specialization point.
struct transposes
Linear algebra transposes specialization point.
struct transposes< Type >
struct transposes< TypedMatrix< Matrix, RowIndexes, ColumnIndexes > >
Specialization of the transposes.
struct typed_matrix
Typed matrix.
Concepts
concept uniform
Every element types of the matrix are the same.
concept in_range
The index is within the range, inclusive.
concept column
The given matrix is a single column.
concept row
The matrix is a single row.
concept one_dimension
The given matrix is a single dimension, that is a row or a column.
concept singleton
The given row and column indexes form a singleton matrix.
concept same_size
The packs have the same count of types.
concept arithmetic
Arithmetic concept.
concept algebraic
Algebraic concept.
concept has_input
Filter input support concept.
concept has_process_uncertainty
Filter process uncertainty support concept.
concept has_output_uncertainty
Filter output uncertainty support concept.
concept has_prediction_types
Filter prediction pack support concept.
concept has_input_control
Filter input control support concept.
concept has_state_transition
Filter state transition support concept.
concept has_update_types
Filter update pack support concept.
concept has_output_model
Filter output model support concept.
Typedefs
template<typename Matrix >
using underlying_t
The underlying storage type of the matrix's elements.
template<typename Matrix , std::size_t RowIndex, std::size_t ColumnIndex>
using element
The type of the element at the given matrix indexes position.
Functions
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes >
constexpr bool operator== (const typed_matrix< Matrix1, RowIndexes, ColumnIndexes > &lhs, const typed_matrix< Matrix2, RowIndexes, ColumnIndexes > &rhs)
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes , typename Indexes >
constexpr auto operator* (const typed_matrix< Matrix1, RowIndexes, Indexes > &lhs, const typed_matrix< Matrix2, Indexes, ColumnIndexes > &rhs)
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
requires singleton<Matrix>
constexpr auto operator* (Scalar lhs, const Matrix &rhs)
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
constexpr auto operator* (Scalar lhs, const typed_matrix< Matrix, RowIndexes, ColumnIndexes > &rhs)
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
requires singleton<Matrix>
constexpr auto operator* (const typed_matrix< Matrix, RowIndexes, ColumnIndexes > &lhs, Scalar rhs)
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
constexpr auto operator* (const typed_matrix< Matrix, RowIndexes, ColumnIndexes > &lhs, Scalar rhs)
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes >
constexpr auto operator+ (const typed_matrix< Matrix1, RowIndexes, ColumnIndexes > &lhs, const typed_matrix< Matrix2, RowIndexes, ColumnIndexes > &rhs)
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
requires singleton<Matrix>
constexpr auto operator+ (const Matrix &lhs, Scalar rhs)
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes >
constexpr auto operator- (const typed_matrix< Matrix1, RowIndexes, ColumnIndexes > &lhs, const typed_matrix< Matrix2, RowIndexes, ColumnIndexes > &rhs)
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
requires singleton<Matrix>
constexpr auto operator- (Scalar lhs, const Matrix &rhs)
template<typename Matrix1 , typename Matrix2 , typename RowIndexes1 , typename RowIndexes2 , typename ColumnIndexes >
constexpr auto operator/ (const typed_matrix< Matrix1, RowIndexes1, ColumnIndexes > &lhs, const typed_matrix< Matrix2, RowIndexes2, ColumnIndexes > &rhs)
template<fcarouge::arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
constexpr auto operator/ (const typed_matrix< Matrix, RowIndexes, ColumnIndexes > &lhs, Scalar rhs)
template<fcarouge::arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes >
requires singleton<Matrix>
constexpr auto operator/ (const Matrix &lhs, Scalar rhs)
Functions
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function >
constexpr void for_constexpr (Function &&function)
Compile-time for loop.
Variables
Algebraic Named Values
template<typename Matrix , typename RowIndexes , typename ColumnIndexes >
typed_matrix< decltype(one< Matrix >), RowIndexes, ColumnIndexes > one< typed_matrix< Matrix, RowIndexes, ColumnIndexes > > {one<Matrix>}
The one matrix specialization.
template<typename Matrix , typename RowIndexes , typename ColumnIndexes >
typed_matrix< decltype(zero< Matrix >), RowIndexes, ColumnIndexes > zero< typed_matrix< Matrix, RowIndexes, ColumnIndexes > > {zero<Matrix>}
The zero matrix specialization.
Named Values
template<typename Pack >
constexpr std::size_t size {internal::size<Pack>}
Size of tuple-like types.
template<auto... Values>
constexpr auto first_v {internal::first_v<Values...>}
Unpack the first value of the non-type template parameter pack.
template<typename Type = double>
constexpr Type one
The one matrix.
template<arithmetic Arithmetic>
constexpr Arithmetic one< Arithmetic > {1}
The singleton one matrix specialization.
template<typename Type >
requires requires { Type::identity(); }
auto one< Type > {Type::Identity()}
template<typename Type = double>
constexpr Type zero
The zero matrix.
template<arithmetic Arithmetic>
constexpr Arithmetic zero< Arithmetic > {0}
The singleton zero matrix specialization.
template<typename Type >
requires requires { Type::zero(); }
auto zero< Type > {Type::Zero()}
Types
template<typename Matrix , typename... ColumnIndexes>
using typed_row_vector
Row vector.
template<typename Matrix , typename... RowIndexes>
using typed_column_vector
Column vector.
template<typename Lhs , typename Rhs >
using quotient
Divider helper type.
template<typename Type >
using evaluate = std::invoke_result_t<evaluates<Type>>
Evaluater helper type.
template<typename Type >
using transpose = std::invoke_result_t<transposes<Type>, const Type &>
Transposer helper type.
using empty_tuple = internal::empty_tuple
Type of the empty tuple.
template<typename... Types>
using first = internal::first<Types...>
Unpack the first type of the type template parameter pack.
template<typename Type , std::size_t Size>
using tuple_n_type = internal::tuple_n_type<Type, Size>
An alias for making a tuple of the same type.
template<typename Lhs , typename Rhs >
using product
Helper type to deduce the result type of the product.
template<typename Lhs , typename Rhs >
using difference
Helper type to deduce the result type of the minus, subtraction.
template<typename Lhs , typename Rhs >
using ᴀʙᵀ = evaluate<product<Lhs, evaluate<transpose<Rhs>>>>
The evaluated type of the ABᵀ expression.
template<typename Type = double, std::size_t Row = 1, std::size_t Column = 1>
using matrix
Scalar type matrix with Eigen implementations.
template<typename Type = double, std::size_t Row = 1>
using column_vector = matrix<Type, Row, 1>
Scalar type column vector with Eigen implementations.
template<typename Type >
auto t (const Type &value)
Transpose helper function.
Detailed Description
Francois Carouge's projects namespace.
The definitions and implementations of the library intended for public usage. Lowers the name conflict probability in large projects. Use using-declarations or namespace-alias-definition per your project guidelines.
Typedef Documentation
ᴀʙᵀ
template<typename Lhs , typename Rhs > using fcarouge::ᴀʙᵀ = evaluate<product<Lhs, evaluate<transpose<Rhs>>>>
The evaluated type of the ABᵀ expression.
Definition at line 216 of file utility.hpp.
column_vector
template<typename Type = double, std::size_t Row = 1> using fcarouge::column_vector = matrix<Type, Row, 1>
Scalar type column vector with Eigen implementations.
Definition at line 57 of file linalg.hpp.
difference
template<typename Lhs , typename Rhs > using fcarouge::difference
Initial value:
    std::invoke_result_t<minus<Lhs, Rhs>, const Lhs &, const Rhs &>
Helper type to deduce the result type of the minus, subtraction.
Definition at line 211 of file utility.hpp.
element
template<typename Matrix , std::size_t RowIndex, std::size_t ColumnIndex> using fcarouge::element
Initial value:
    product<std::tuple_element_t<RowIndex, typename Matrix::row_indexes>,
            std::tuple_element_t<ColumnIndex, typename Matrix::column_indexes>>
The type of the element at the given matrix indexes position.
Definition at line 57 of file typed_linear_algebra.hpp.
empty_tuple
using fcarouge::empty_tuple = internal::empty_tuple
Type of the empty tuple.
A tuple with no pack types.
Definition at line 181 of file utility.hpp.
evaluate
template<typename Type > using fcarouge::evaluate = std::invoke_result_t<evaluates<Type>>
Evaluater helper type.
Definition at line 150 of file utility.hpp.
first
template<typename... Types> using fcarouge::first = internal::first<Types...>
Unpack the first type of the type template parameter pack.
Shorthand for std::tuple_element_t<0, std::tuple<Types...>>.
Definition at line 186 of file utility.hpp.
matrix
template<typename Type = double, std::size_t Row = 1, std::size_t Column = 1> using fcarouge::matrix
Initial value:
    typed_matrix<eigen::matrix<Type, Row, Column>, tuple_n_type<Type, Row>,
                 tuple_n_type<Type, Column>>
Scalar type matrix with Eigen implementations.
Definition at line 51 of file linalg.hpp.
product
template<typename Lhs , typename Rhs > using fcarouge::product
Initial value:
    std::invoke_result_t<multiplies<Lhs, Rhs>, const Lhs &, const Rhs &>
Helper type to deduce the result type of the product.
Definition at line 200 of file utility.hpp.
quotient
template<typename Lhs , typename Rhs > using fcarouge::quotient
Initial value:
    std::invoke_result_t<divides<Lhs, Rhs>, const Lhs &, const Rhs &>
Divider helper type.
Definition at line 140 of file utility.hpp.
transpose
template<typename Type > using fcarouge::transpose = std::invoke_result_t<transposes<Type>, const Type &>
Transposer helper type.
Definition at line 169 of file utility.hpp.
tuple_n_type
template<typename Type , std::size_t Size> using fcarouge::tuple_n_type = internal::tuple_n_type<Type, Size>
An alias for making a tuple of the same type.
Definition at line 190 of file utility.hpp.
typed_column_vector
template<typename Matrix , typename... RowIndexes> using fcarouge::typed_column_vector
Initial value:
    typed_matrix<Matrix, std::tuple<RowIndexes...>, std::tuple<int>>
Column vector.
Definition at line 328 of file typed_linear_algebra.hpp.
typed_row_vector
template<typename Matrix , typename... ColumnIndexes> using fcarouge::typed_row_vector
Initial value:
    typed_matrix<Matrix, std::tuple<int>, std::tuple<ColumnIndexes...>>
Row vector.
Definition at line 323 of file typed_linear_algebra.hpp.
underlying_t
template<typename Matrix > using fcarouge::underlying_t
Initial value:
    std::remove_cvref_t<decltype(std::declval<Matrix>()(0, 0))>
The underlying storage type of the matrix's elements.
Definition at line 52 of file typed_linear_algebra.hpp.
Function Documentation
for_constexpr()
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function > void fcarouge::for_constexpr (Function && function) inline constexpr
Compile-time for loop.
Help compilers with non-type template parameters on members.
Definition at line 228 of file utility.hpp.
{
  internal::for_constexpr<Begin, End, Increment>(
      std::forward<Function>(function));
}
References fcarouge::internal::for_constexpr().
Referenced by fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::typed_matrix().
operator*() [1/5]
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > requires singleton<Matrix> auto fcarouge::operator* (const typed_matrix< Matrix, RowIndexes, ColumnIndexes > & lhs, Scalar rhs) inline nodiscard constexpr
Definition at line 370 of file typed_linear_algebra.hpp.
                      {
  return element<Matrix, 0, 0>{lhs.data(0) * rhs};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator*() [2/5]
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > auto fcarouge::operator* (const typed_matrix< Matrix, RowIndexes, ColumnIndexes > & lhs, Scalar rhs) inline nodiscard constexpr
Definition at line 378 of file typed_linear_algebra.hpp.
                      {
  return typed_matrix<evaluate<Matrix>, RowIndexes, ColumnIndexes>{lhs.data *
                                                                   rhs};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator*() [3/5]
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes , typename Indexes > auto fcarouge::operator* (const typed_matrix< Matrix1, RowIndexes, Indexes > & lhs, const typed_matrix< Matrix2, Indexes, ColumnIndexes > & rhs) inline nodiscard constexpr
Definition at line 344 of file typed_linear_algebra.hpp.
{
  return typed_matrix<evaluate<product<Matrix1, Matrix2>>, RowIndexes,
                      ColumnIndexes>{lhs.data * rhs.data};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator*() [4/5]
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > requires singleton<Matrix> auto fcarouge::operator* (Scalar lhs, const Matrix & rhs) inline nodiscard constexpr
Definition at line 353 of file typed_linear_algebra.hpp.
{
  return element<Matrix, 0, 0>{lhs * rhs.data(0)};
}
operator*() [5/5]
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > auto fcarouge::operator* (Scalar lhs, const typed_matrix< Matrix, RowIndexes, ColumnIndexes > & rhs) inline nodiscard constexpr
Definition at line 360 of file typed_linear_algebra.hpp.
{
  return typed_matrix<evaluate<Matrix>, RowIndexes, ColumnIndexes>{lhs *
                                                                   rhs.data};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator+() [1/2]
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > requires singleton<Matrix> auto fcarouge::operator+ (const Matrix & lhs, Scalar rhs) inline nodiscard constexpr
Todo
Scalar will become Index with constraints.
Definition at line 396 of file typed_linear_algebra.hpp.
{
  return element<Matrix, 0, 0>{lhs.data(0) + rhs};
}
operator+() [2/2]
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes > auto fcarouge::operator+ (const typed_matrix< Matrix1, RowIndexes, ColumnIndexes > & lhs, const typed_matrix< Matrix2, RowIndexes, ColumnIndexes > & rhs) inline nodiscard constexpr
Definition at line 387 of file typed_linear_algebra.hpp.
{
  return typed_matrix<evaluate<Matrix1>, RowIndexes, ColumnIndexes>{lhs.data +
                                                                    rhs.data};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator-() [1/2]
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes > auto fcarouge::operator- (const typed_matrix< Matrix1, RowIndexes, ColumnIndexes > & lhs, const typed_matrix< Matrix2, RowIndexes, ColumnIndexes > & rhs) inline nodiscard constexpr
Definition at line 404 of file typed_linear_algebra.hpp.
{
  return typed_matrix<evaluate<Matrix1>, RowIndexes, ColumnIndexes>{lhs.data -
                                                                    rhs.data};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator-() [2/2]
template<arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > requires singleton<Matrix> auto fcarouge::operator- (Scalar lhs, const Matrix & rhs) inline nodiscard constexpr
Definition at line 413 of file typed_linear_algebra.hpp.
{
  return element<Matrix, 0, 0>{lhs - rhs.data(0)};
}
operator/() [1/3]
template<fcarouge::arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > requires singleton<Matrix> auto fcarouge::operator/ (const Matrix & lhs, Scalar rhs) inline nodiscard constexpr
Definition at line 438 of file typed_linear_algebra.hpp.
{
  return element<Matrix, 0, 0>{lhs.data(0) / rhs};
}
operator/() [2/3]
template<fcarouge::arithmetic Scalar, typename Matrix , typename RowIndexes , typename ColumnIndexes > auto fcarouge::operator/ (const typed_matrix< Matrix, RowIndexes, ColumnIndexes > & lhs, Scalar rhs) inline nodiscard constexpr
Definition at line 429 of file typed_linear_algebra.hpp.
                      {
  return typed_matrix<evaluate<Matrix>, RowIndexes, ColumnIndexes>{lhs.data /
                                                                   rhs};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator/() [3/3]
template<typename Matrix1 , typename Matrix2 , typename RowIndexes1 , typename RowIndexes2 , typename ColumnIndexes > auto fcarouge::operator/ (const typed_matrix< Matrix1, RowIndexes1, ColumnIndexes > & lhs, const typed_matrix< Matrix2, RowIndexes2, ColumnIndexes > & rhs) inline nodiscard constexpr
Definition at line 420 of file typed_linear_algebra.hpp.
{
  return typed_matrix<evaluate<quotient<Matrix1, Matrix2>>, RowIndexes1,
                      RowIndexes2>{lhs.data / rhs.data};
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
operator==()
template<typename Matrix1 , typename Matrix2 , typename RowIndexes , typename ColumnIndexes > bool fcarouge::operator== (const typed_matrix< Matrix1, RowIndexes, ColumnIndexes > & lhs, const typed_matrix< Matrix2, RowIndexes, ColumnIndexes > & rhs) inline nodiscard constexpr
Definition at line 336 of file typed_linear_algebra.hpp.
{
  return lhs.data == rhs.data;
}
References fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::data.
t()
template<typename Type > auto fcarouge::t (const Type & value)
Transpose helper function.
Enable readable linear algebra notation.
Definition at line 174 of file utility.hpp.
{
  return transposes<Type>{}(value);
}
Referenced by fcarouge::transposes< TypedMatrix< Matrix, RowIndexes, ColumnIndexes > >::operator()().
Variable Documentation
first_v
template<auto... Values> auto fcarouge::first_v {internal::first_v<Values...>} inline constexpr
Unpack the first value of the non-type template parameter pack.
Definition at line 246 of file utility.hpp.
{internal::first_v<Values...>};
one
template<typename Type = double> Type fcarouge::one inline constexpr
Initial value:
{internal::not_implemented<Type>{
    "Implement the linear algebra one-diagonal matrix for this type."}}
The one matrix.
User-defined matrix with all its diagonal elements equal to ones, and zeroes everywhere else. This matrix is also known as the identity matrix for square matrices of non-quantity scalar types.
Definition at line 254 of file utility.hpp.
                         {internal::not_implemented<Type>{
    "Implement the linear algebra one-diagonal matrix for this type."}};
one< Arithmetic >
template<arithmetic Arithmetic> Arithmetic fcarouge::one< Arithmetic > {1} inline constexpr
The singleton one matrix specialization.
Definition at line 258 of file utility.hpp.
{1};
one< Type >
template<typename Type > requires requires { Type::identity(); } auto fcarouge::one< Type > {Type::Identity()} inline
Definition at line 262 of file utility.hpp.
{Type::Identity()};
one< typed_matrix< Matrix, RowIndexes, ColumnIndexes > >
template<typename Matrix , typename RowIndexes , typename ColumnIndexes > typed_matrix<decltype(one<Matrix>), RowIndexes, ColumnIndexes> fcarouge::one< typed_matrix< Matrix, RowIndexes, ColumnIndexes > > {one<Matrix>} inline
The one matrix specialization.
Definition at line 509 of file typed_linear_algebra.hpp.
{one<Matrix>};
size
template<typename Pack > std::size_t fcarouge::size {internal::size<Pack>} inline constexpr
Size of tuple-like types.
Convenient short form. In place of std::tuple_size_v.
Definition at line 242 of file utility.hpp.
{internal::size<Pack>};
zero
template<typename Type = double> Type fcarouge::zero inline constexpr
Initial value:
{internal::not_implemented<Type>{
    "Implement the linear algebra zero matrix for this type."}}
The zero matrix.
User-defined.
Definition at line 272 of file utility.hpp.
                          {internal::not_implemented<Type>{
    "Implement the linear algebra zero matrix for this type."}};
zero< Arithmetic >
template<arithmetic Arithmetic> Arithmetic fcarouge::zero< Arithmetic > {0} inline constexpr
The singleton zero matrix specialization.
Definition at line 277 of file utility.hpp.
{0};
zero< Type >
template<typename Type > requires requires { Type::zero(); } auto fcarouge::zero< Type > {Type::Zero()} inline
Definition at line 281 of file utility.hpp.
{Type::Zero()};
zero< typed_matrix< Matrix, RowIndexes, ColumnIndexes > >
template<typename Matrix , typename RowIndexes , typename ColumnIndexes > typed_matrix<decltype(zero<Matrix>), RowIndexes, ColumnIndexes> fcarouge::zero< typed_matrix< Matrix, RowIndexes, ColumnIndexes > > {zero<Matrix>} inline
The zero matrix specialization.
Definition at line 509 of file typed_linear_algebra.hpp.
{zero<Matrix>};