Typed Linear Algebra: fcarouge::typed_linear_algebra_internal Namespace Reference
fcarouge::typed_linear_algebra_internal Namespace Reference
Classes
struct divides
Linear algebra divides expression type specialization point.
struct element_traits
Element traits for conversions.
struct evaluates
Linear algebra evaluates override expression lazy evaluation specialization point.
struct evaluates< Type >
Specialization of the evaluation type.
struct multiplies
Type multiplies expression type specialization point.
struct multiplies< std::type_identity< void >, Type >
struct multiplies< Type, std::type_identity< void > >
struct repacker
struct repacker< Pack< Types... > >
struct transposes
Linear algebra transposes specialization point.
struct transposes< Type >
struct tupler
Typedefs
template<typename Lhs , typename Rhs >
using quotient
Divider helper type.
template<typename Lhs , typename Rhs >
using product
Helper type to deduce the result type of the product.
template<typename Type >
using evaluate = std::invoke_result_t<evaluates<Type>>
Evaluater helper type.
template<typename Pack >
using repack = repacker<Pack>::type
template<typename Matrix >
using underlying_t
The underlying storage type of the matrix's elements.
template<typename Matrix , std::size_t RowIndex, std::size_t ColumnIndex>
using element
The type of the element at the given matrix indexes position.
template<typename Type >
using transpose = std::invoke_result_t<transposes<Type>, const Type &>
Transposer helper type.
template<typename Type , std::size_t Size>
using tuple_n_type = typename tupler<Type, Size>::type
An alias for making a tuple of the same type.
using identity_index = std::tuple<std::type_identity<void>>
One-element transparent tuple index.
Functions
Functions
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function >
constexpr void for_constexpr (Function &&function)
Compile-time for loop.
Variables
template<typename Pack >
constexpr std::size_t size {repacker<Pack>::size}
Size of tuple-like types.
Typedef Documentation
element
template<typename Matrix , std::size_t RowIndex, std::size_t ColumnIndex> using fcarouge::typed_linear_algebra_internal::element
Initial value:
    product<std::tuple_element_t<RowIndex, typename Matrix::row_indexes>,
            std::tuple_element_t<ColumnIndex, typename Matrix::column_indexes>>
The type of the element at the given matrix indexes position.
Definition at line 145 of file utility.hpp.
evaluate
template<typename Type > using fcarouge::typed_linear_algebra_internal::evaluate = std::invoke_result_t<evaluates<Type>>
Evaluater helper type.
Definition at line 79 of file utility.hpp.
identity_index
using fcarouge::typed_linear_algebra_internal::identity_index = std::tuple<std::type_identity<void>>
One-element transparent tuple index.
Definition at line 245 of file utility.hpp.
product
template<typename Lhs , typename Rhs > using fcarouge::typed_linear_algebra_internal::product
Initial value:
    std::invoke_result_t<multiplies<Lhs, Rhs>, const Lhs &, const Rhs &>
Helper type to deduce the result type of the product.
Definition at line 69 of file utility.hpp.
quotient
template<typename Lhs , typename Rhs > using fcarouge::typed_linear_algebra_internal::quotient
Initial value:
    std::invoke_result_t<divides<Lhs, Rhs>, const Lhs &, const Rhs &>
Divider helper type.
Definition at line 58 of file utility.hpp.
repack
template<typename Pack > using fcarouge::typed_linear_algebra_internal::repack = repacker<Pack>::type
Definition at line 110 of file utility.hpp.
transpose
template<typename Type > using fcarouge::typed_linear_algebra_internal::transpose = std::invoke_result_t<transposes<Type>, const Type &>
Transposer helper type.
Definition at line 225 of file utility.hpp.
tuple_n_type
template<typename Type , std::size_t Size> using fcarouge::typed_linear_algebra_internal::tuple_n_type = typename tupler<Type, Size>::type
An alias for making a tuple of the same type.
Definition at line 242 of file utility.hpp.
underlying_t
template<typename Matrix > using fcarouge::typed_linear_algebra_internal::underlying_t
Initial value:
    std::remove_cvref_t<decltype(std::declval<Matrix>()(0, 0))>
The underlying storage type of the matrix's elements.
Definition at line 140 of file utility.hpp.
Function Documentation
for_constexpr()
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function > void fcarouge::typed_linear_algebra_internal::for_constexpr (Function && function) inline constexpr
Compile-time for loop.
Help compilers with non-type template parameters on members.
Definition at line 89 of file utility.hpp.
{
  if constexpr (Begin < End) {
    function(std::integral_constant<std::size_t, Begin>());
    for_constexpr<Begin + Increment, End, Increment>(
        std::forward<Function>(function));
  }
}
References for_constexpr().
Referenced by for_constexpr(), and fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >::typed_matrix().
Variable Documentation
size
template<typename Pack > std::size_t fcarouge::typed_linear_algebra_internal::size {repacker<Pack>::size} inline constexpr
Size of tuple-like types.
Convenient short form. In place of std::tuple_size_v.
Definition at line 116 of file utility.hpp.
{repacker<Pack>::size};